# Test automated pull requests
name: Automated-Pull-Request

on:
  push:
    branches: [ from-projectA ]

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "👑 *An automated PR*"
          pr_reviewer: "ddsharpe"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}